### ISSUE TITLE
好像出错了，无法执行下去，是我的目录错了吗

### ISSUE THREAD

**Issue by menendezt** [ChenJunsen/StarboundAutoTranslator#1]
Error: ENOENT: no such file or directory, stat 'G:\GITStarboundCHN\FrackinUniverse-sChinese-Project\translations\patches'
    at Object.statSync (node:fs:1551:3)
    at loopFile (G:\GIT\StarboundCHN\quicktranslate\src\module\file.js:14:26)
    at Object.<anonymous> (G:\GIT\StarboundCHN\quicktranslate\src\exe.js:8:18)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  errno: -4058,
  syscall: 'stat',
  code: 'ENOENT',
  path: 'G:\\GITStarboundCHN\\FrackinUniverse-sChinese-Project\\translations\\patches'
}

**Comment by ChenJunsen** [comment]
把你翻译的那个文件粘上来看看，这个工具是很久之前的了，我这边还有一个进阶版的，你可以试试那个

**Comment by menendezt** [comment]
我好像回复错地方了。。这个错误是进阶版的使用nodejs那个翻译机版本的问题，我选择的目录是包含未翻译文件的根目录，但是好像因为之前我用系统语言是繁体，导致开始后出现乱码，然后我把start.bat中的color 0d到欢迎使用那两条代码删除了，还是一样无法使用。大佬可以帮忙分析下吗

**Comment by ChenJunsen** [comment]
project.config.js里面的待翻译目录配对没，看报错，是没有找到目录。
`color 0d
title 屎大棒富兰克林宇宙本自动翻译机
echo =========欢迎使用文本自动翻译机========`
这三行删除并不影响实际效果哇

**Comment by ChenJunsen** [comment]
另外，你那个目录直接指向patch文件夹，不建议这么做。patch文件夹太大了，先不说翻译时间，可以能会报内存错误。建议选到小点的文件夹翻译。这样也好翻译完校对。

**Comment by menendezt** [comment]
好的，我回家后确认一下。我记得我是按照说明每个反斜杠都是加了一个反斜杠转义的。。
另外问一下如果我想指定一个目录，最后一个文件夹需要加反斜杠吗？
如G:\\github\\

**Comment by ChenJunsen** [comment]
![image](https://user-images.githubusercontent.com/22163218/179165055-38a22376-07a6-4d99-abac-113d25fc58e6.png)
